### ISSUE TITLE
SettingsApi Activity should return RESULT_OK

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#151]
### Description
Currently, `Status#startResolutionForResult` starts an `Activity` that does not finish with `RESULT_OK`. Instead, developers rely on the `requestCode` to determine application flow. As per https://github.com/mapzen/lost/pull/150 we should try:

Wrapping `SettingsDialogFragment` in its own `Activity` which could perform an additional location settings check when the user returns from the system settings menu. Then if the settings have been updated by the user it could finish itself with RESULT_OK.

Of course then we would also need a way to pass the original `LocationSettingsRequest` into the wrapper `Activity` so it could verify location settings requirements have been met.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
