### ISSUE TITLE
Add Testing Utils

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#157]
As mentioned (https://github.com/mapzen/android/pull/260), it requires a LOT of setup to properly test calls to `LocationServices.FusedLocationApi`

Lets provide a way to do this for developers:
```
    FusedLocationProviderService.FusedLocationProviderBinder stubBinder =
          mock(FusedLocationProviderService.FusedLocationProviderBinder.class);
    FusedLocationProviderService mockService = mock(FusedLocationProviderService.class);
      when(stubBinder.getService()).thenReturn(mockService);
    FusedLocationProviderApiImpl impl =
        (FusedLocationProviderApiImpl) LocationServices.FusedLocationApi;
    impl.onServiceConnected(stubBinder);

```

Initial implementation ideas:
- Expose the `FusedLocationProvider` service with `@VisibleForTesting` annotation 
- Create a separate artifact that adds classes to wrap these calls

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
