### ISSUE TITLE
[question] Is setInterval mandatory since v2.0?

### ISSUE THREAD

**Issue by Guardiola31337** [lostzen/lost#171]
Per https://github.com/mapbox/mapbox-java/pull/393#issue-214960653
Is update interval (`setInterval`) call mandatory to create a request (`LocationRequest`) since v2.0?
If so, would it make sense to add this in the [upgrading guide](https://github.com/mapzen/lost/blob/master/docs/upgrade-1x-2.md)?

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
