### ISSUE TITLE
Revisit hardware requirements

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#176]
From the [docs](https://developer.android.com/guide/topics/manifest/uses-feature-element.html):
"Declared <uses-feature> elements are informational only, meaning that the Android system itself does not check for matching feature support on the device before installing an application"

We should consider making our hardware requirements optional and have application developers declare these values as non-optional if they need. This would be more consistent with how we handle manifest permissions.

**Comment by Guardiola31337** [comment]
@sarahlensing that'd be great because the [same thing happens with the WiFi permission](https://github.com/mapzen/lost/issues/169#issuecomment-288971298) 👍

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
