### ISSUE TITLE
[question][enhancement][feature] Wear support

### ISSUE THREAD

**Issue by Guardiola31337** [lostzen/lost#177]
As commented [here](https://github.com/mapzen/lost/issues/169#issuecomment-288971298):

There are watches with and without GPS and Google's library does the wiring automatically so when you have a watch without GPS paired with a mobile you still receive updates using same APIs.

You can see below that using [normal location APIs](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidWearDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/GoogleLocationEngine.java) (there aren't any concrete wear APIs) you get the updates in a watch without GPS:

![trackinglocationwear](https://cloud.githubusercontent.com/assets/1668582/24287524/5da71eaa-107a-11e7-8198-a8b836399d21.gif)

It'd be awesome to have same functionality in Lost ❤️ 
Are you planning to support it?

Thanks @ecgreb @sarahlensing

**Comment by ecgreb** [comment]
There are no specific plans or timeline for Android Wear support right now but this would certainly be a nice feature to have.

It should still be possible to use Lost with Android Wear currently if you manually forward the location updates.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
