### ISSUE TITLE
Improve build memory limits

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#192]
Our builds are frequently failing because they hit the 4G memory limit on circle:
`Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named `memory-usage.txt`. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes.`

We should look at the `memory-usage.txt` and consider limiting the JVM's usage with `_JAVA_OPTIONS`: https://circleci.com/docs/1.0/oom/

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
