### ISSUE TITLE
Implement GeofenceStatusCodes

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#204]
`GeofencingEvent` defines status codes:
```
public static final int GEOFENCE_NOT_AVAILABLE = 1000;
public static final int GEOFENCE_TOO_MANY_GEOFENCES = 1001;
public static final int GEOFENCE_TOO_MANY_PENDING_INTENTS = 1002;
```

but `GeofencingApiImpl` always returns a `SimplePendingResult` with `SUCCESS` status.

1. Update the result to return a proper status code.
2. Update `GeofencingEvent#getErrorCode ()` to return the status code if an error exists (currently it returns 0)
3. Consider moving these constants into a new `GeofencseStatusCodes` class and adding static method `getStatusCodeString(int statusCode)`.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
