### ISSUE TITLE
Simplify FusedLocationProvider Internal Check

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#214]
Because `LocationEngine#removeRequest` disables and re-enables the engine (if there are still remaining requests), we no longer need to check to see if the engine should be disabled in `FusedLocationProviderApi#checkAllListenersPendingIntentsAndCallbacks` but as @ecgreb [pointed out](https://github.com/mapzen/lost/pull/215) we could as an enhancement call `LocationEngine#removeAllRequests` when the last client is disconnected "to avoid this issue of needing to explicitly remove all requests before shutting down a client"

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
