### ISSUE TITLE
Investigate Updating ConnectionCallbacks Interface

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#219]
Provide suspension causes in `onConnectionSuspended` and bundle in `onConnected`

https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/api/LostApiClient.java

https://developers.google.com/android/reference/com/google/android/gms/common/api/GoogleApiClient.ConnectionCallbacks

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
