### ISSUE TITLE
Feature Request: Avoid waiting long time to receive a new location

### ISSUE THREAD

**Issue by 13kz** [lostzen/lost#220]
### Problematic
In indoor for example, user can wait a long time to receive a new location.

### Proposal
So to avoid this, you can have a kind of timer started when lost api client is connected and trigger an event (which post the last known location) after x seconds without a new location. 
The timer is restarted when a new location is received and stopped before disconnecting lost api client.

The client of the SDK decides:

- to enable it

- the interval to re-post the last known location

**Comment by msmollin** [comment]
Thanks for the feature enhancement. I agree we could probably do a better job with managing indoor location difficulties. Have you happened to see how Google Play Services handles this particular problem? What is the particular use case you're attempting to resolve with this?

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
