### ISSUE TITLE
Sample : No locations received when putting the app to background and bringing back to foreground. .

### ISSUE THREAD

**Issue by 13kz** [lostzen/lost#221]
### Description
Connect lost api client, request location updates and receive locations back to foreground (in onPause method you disconnect the client and connect it in onResume method).

Knowing that, you build the client by adding the connection callback in onCreate, remove location listener, disconnect the client and unregister connection callback in on Pause, so when bringing back the sample to foreground you connect the client but the connection callback is missing.
The onConnected is never called and requestLocationUpdates too.

### Steps to Reproduce
Put the LocationListenerActivity sample to background and bring back to foreground. No locations received.

**Comment by msmollin** [comment]
Thanks for the report! This revealed some unimplemented APIs we should add to ease this problem. See #222 for relevant information. In the mean time this can be worked around by modifying the sample such that when `onResume` is called, destroy the API client and re-create it.

We'll work on updating the sample as part of the work on #222.

**Comment by 13kz** [comment]
thanks @msmollin. So can i close this one?

**Comment by msmollin** [comment]
It's fine to leave it open just as a reminder for us.

**Comment by Guardiola31337** [comment]
Hey @msmollin 👋
Does https://github.com/mapzen/lost/issues/241 could be because of OP?

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
