### ISSUE TITLE
Provide APIs to handle checked exceptions

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#229]
Currently, Lost can ([and occasionally does](https://github.com/mapzen/lost/issues/218)) throw `RemoteExceptions` when making calls to/from the service. Since these are checked exceptions, we should provide a way for the developer to handle recovering from them instead of re-throwing `RuntimeException`s. This task will require significant testing but will ultimately result in the addition of new APIs on `LocationServices`.

- [x] Replace `RuntimeException`s with `Log.e` (https://github.com/mapzen/lost/pull/230)
- [ ] Add [`FusedLocationProviderClient`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient) and return `null` for all method calls
- [ ] Update `LocationServices` to handle `FusedLocationProviderClient` objects
- [ ] Add [`Task`](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task)
- [ ] Add [`OnFailureListener`](https://developers.google.com/android/reference/com/google/android/gms/tasks/OnFailureListener)
- [ ] Update `FusedLocationProviderClient` to return `Task`s

There will be more work beyond this required to fully implement all the APIs around this feature but this should cover the first chunk necessary for a useful feature. A future ticket will detail out extended APIs to implement

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
