### ISSUE TITLE
Remove use of Location#getTime or bump min API

### ISSUE THREAD

**Issue by sarahlensing** [lostzen/lost#243]
We should not be using `Location#getTime` for elapsed time computation but are doing so for earlier versions of Android because `Location#getElapsedRealtimeNano` is not available.

https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/SystemClock.java#L13-L19
https://developer.android.com/reference/android/location/Location.html#getElapsedRealtimeNanos()

Consider creating another, reliable way to compute this value or modifying LOST to workaround this while still respecting `LocationRequest#fastestInterval`. Alternatively, evaluate bumping the minimum SDK required from 15 to 17 (this would drop support for 3% of users).

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
