### ISSUE TITLE
Cannot use Geofence

### ISSUE THREAD

**Issue by Alex237** [lostzen/lost#252]
### Description
Hello, I am trying to use Geofence with lost API, but i have so crashes when i am near my point. 
I have the following error 
```Java
E/AndroidRuntime: FATAL EXCEPTION: IntentService[GeofencingIntentService]
                  Process: com.upmc.mapmasterquest, PID: 20979
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapzen.android.lost.internal.ParcelableGeofence.getTransitionTypes()' on a null object reference
                      at com.mapzen.android.lost.api.GeofencingIntentSender.shouldSendIntent(GeofencingIntentSender.java:54)
                      at com.mapzen.android.lost.api.GeofencingIntentSender.sendIntent(GeofencingIntentSender.java:35)
                      at com.mapzen.android.lost.internal.GeofencingIntentService.onHandleIntent(GeofencingIntentService.java:25)
                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.os.HandlerThread.run(HandlerThread.java:61)
```
### Steps to Reproduce

1. In my activity, Connect my LostClient
2. Request location updates
3. Create my Geofence
```Java
protected void createGeofence(LostApiClient client) {
        double latitude = FakeLatitudeForTest;
        double longitude = FakeLongitudeForTest;
        float radius = 500;

        Geofence geofence = new Geofence.Builder()
                .setRequestId("RandomId")
                .setCircularRegion(latitude, longitude, radius)
                .setTransitionTypes(GEOFENCE_TRANSITION_ENTER | GEOFENCE_TRANSITION_EXIT | GEOFENCE_TRANSITION_DWELL)
                .setLoiteringDelay(10000)
                .setExpirationDuration(NEVER_EXPIRE)
                .build();

        GeofencingRequest request = new GeofencingRequest.Builder()
                .addGeofence(geofence)
                .build();

        // context is already defined, i re-use it here
        Intent serviceIntent = new Intent(context, GeofenceIntent.class);
        pendingIntent = PendingIntent.getService(getActivity(), 0, serviceIntent, 0);

        LocationServices.GeofencingApi.addGeofences(client, request, pendingIntent);
    }
```

### Lost & Android Version
I am using `Lost 3.0.4` on an an Emulator (Nexus 4 - Android 6 -  API 23)

thank for your help :)`;

**Comment by sarahlensing** [comment]
Thanks for the report, are you able to reproduce on a device as well?

**Comment by joe-average-user** [comment]
Yes, here:

03-31 10:34:01.148 15952 16929 E AndroidRuntime: FATAL EXCEPTION: IntentService[GeofencingIntentService]
03-31 10:34:01.148 15952 16929 E AndroidRuntime: Process: org.nexttracks.android, PID: 15952
03-31 10:34:01.148 15952 16929 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapzen.android.lost.internal.ParcelableGeofence.getTransitionTypes()' on a null object reference
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at com.mapzen.android.lost.api.GeofencingIntentSender.shouldSendIntent(GeofencingIntentSender.java:54)
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at com.mapzen.android.lost.api.GeofencingIntentSender.sendIntent(GeofencingIntentSender.java:35)
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at com.mapzen.android.lost.internal.GeofencingIntentService.onHandleIntent(GeofencingIntentService.java:25)
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-31 10:34:01.148 15952 16929 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-31 10:34:01.151  1284 16930 I chatty  : uid=1000 system_server expire 1 line
03-31 10:34:01.170  1284  1284 I chatty  : uid=1000 system_server expire 46 lines
03-31 10:34:01.180  1284  3055 I chatty  : uid=1000(system) Binder:1284_C expire 1 line
03-31 10:34:01.181  1284  4002 I chatty  : uid=1000(system) Binder:1284_14 expire 8 lines
03-31 10:34:01.185  1284  1311 I chatty  : uid=1000(system) android.display expire 19 lines
03-31 10:34:01.202  1284  1318 I chatty  : uid=1000(system) ActivityManager expire 14 lines
03-31 10:34:01.272 16940 16967 E AndroidRuntime: FATAL EXCEPTION: IntentService[GeofencingIntentService]
03-31 10:34:01.272 16940 16967 E AndroidRuntime: Process: org.nexttracks.android, PID: 16940
03-31 10:34:01.272 16940 16967 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapzen.android.lost.internal.ParcelableGeofence.getTransitionTypes()' on a null object reference
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at com.mapzen.android.lost.api.GeofencingIntentSender.shouldSendIntent(GeofencingIntentSender.java:54)
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at com.mapzen.android.lost.api.GeofencingIntentSender.sendIntent(GeofencingIntentSender.java:35)
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at com.mapzen.android.lost.internal.GeofencingIntentService.onHandleIntent(GeofencingIntentService.java:25)
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-31 10:34:01.272 16940 16967 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)

Which is a
Bus 002 Device 008: ID 18d1:4ee1 Google Inc. Nexus Device (MTP)

with latest Android 10.

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
