### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by tananaev** [lostzen/lost#253]
What are the plans for this open source project in the light of the recent news that Mapzen is ceasing operations?

https://mapzen.com/blog/shutdown/

**Comment by sarahlensing** [comment]
Luckily Lost is not part of the hosted services which will no longer be offered. This project will continue to exist in the open as it always has, it won't be going away. The biggest change to Lost will be the time it takes us to complete new features as we get settled into new roles. Pull requests are always welcome though!

**Comment by tananaev** [comment]
Great, thanks. I was a bit worried because I use your project in one of my open source Android apps.
