### ISSUE TITLE
Geofencing and Background Location support in Oreo (API 26+)

### ISSUE THREAD

**Issue by electrostat** [lostzen/lost#259]
### Description
Are there plans for updating Lost for Oreo support? Specifically, what are the plans to keep geofencing working in the background? 

### Steps to Reproduce
Run Lost on Android Oreo.

### Lost & Android Version
Android 8.0 + 8.1, Lost 3.0.4

cc: @sarahlensing

**Comment by msmollin** [comment]
Closing as this repo is no longer maintained.
