### ISSUE TITLE
Archive unmaintained repository

### ISSUE THREAD

**Issue by rugk** [lostzen/lost#271]
You can [archive this repository](https://docs.github.com/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository/archiving-repositories), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

As this does not look very maintained anymore…

**Comment by msmollin** [comment]
Done
