### ISSUE TITLE
Need to add  android:exported="true" for GeofencingIntentService in AndroidManifest to support TargetApiLevel > 31

### ISSUE THREAD

**Issue by ganeshbahirat** [lostzen/lost#272]
**This is suggestion not an issue.**

Need to add  android:exported="true" for GeofencingIntentService in AndroidManifest to support TargetApiLevel > 31

**Comment by nyinyihtunlwin-codigo** [comment]
Any update on this case?

**Comment by nyinyihtunlwin-codigo** [comment]
This issue can be solved by these steps

1. Add below code block in **AndroidManifest.xml** file of your project. (between **<application>  </application>** ).

**```
<service
            android:name="com.mapzen.android.lost.internal.GeofencingIntentService"
            android:exported="true"
            tools:replace="android:exported" />
```**
2. Add **android.enableJetifier=true** in **grade.properties** file for old android module conflicts.

**Comment by msmollin** [comment]
Hi @nyinyihtunlwin-codigo this repository is being closed down as it is no longer maintained.
